### ISSUE TITLE
Implement better error/exception catching

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-amazon-s3#15]
We need to expose error for common issues, like wrong API keys, incorrect bucket permissions, etc. Here's an example debug.log from a customer that can't view his bucket list:
```
[10-Sep-2015 07:32:22 UTC] PHP Fatal error:  Uncaught exception 'S3Exception' with message 'S3::listBuckets(): [AccessDenied] Access Denied' in /public_html/wp-content/plugins/edd-amazon-s3/s3.php:374
Stack trace:
#0 /public_html/wp-content/plugins/edd-amazon-s3/s3.php(374): S3::__triggerError('S3::listBuckets...', '/...', 374)
#1 /public_html/wp-content/plugins/edd-amazon-s3/edd_s3.php(407): S3::listBuckets()
#2 /public_html/wp-content/plugins/edd-amazon-s3/edd_s3.php(243): EDD_Amazon_S3::get_s3_buckets()
#3 [internal function]: EDD_Amazon_S3::s3_upload_download_tab()
#4 /public_html/wp-admin/includes/media.php(518): call_user_func_array(Array, Array)
#5 /public_html/wp-content/plugins/edd-amazon-s3/edd_s3.php(206): wp_iframe(Array)
#6 [internal function]: EDD_Amazon_S3->s3_upload_iframe('')
#7 /public_html/wp-includes/plugin.php(503): call_user_func_array(Array, Array)
#8 /public_html/wp-admin/media-upload.php(101): do_action(' in /public_html/wp-content/plugins/edd-amazon-s3/s3.php on line 374
```

In this case, there is no user-facing message. The customer just sees an empty screen on the Amazon tab.

**Comment by pippinsplugins** [comment]
Note, this will require direct modifications to the S3 API file. It's really out dated any way so shouldn't hurt. We could also consider updating to a new version of the API library.

**Comment by cklosowski** [comment]
Ok, this update does 2 things. Throws an admin notice if the key or secret are empty. Should cut down on tickets from that end.

Also, instead of using the `trigger_error` function when a file cannot be delivered, we add an error to `edd_add_error()`, then upon delivering the file, if we identify that EDD_Amazon_S3 has thrown an error, we use `wp_die()` to give a specific message to the admins, and a generic message to end users.

**Comment by cklosowski** [comment]
![screen shot 2015-09-15 at 6 41 30 pm](https://cloud.githubusercontent.com/assets/1390124/9894842/7ad5874e-5bdd-11e5-8ae4-c71e2f5a44af.png)

**Comment by cklosowski** [comment]
![screen shot 2015-09-15 at 6 59 38 pm](https://cloud.githubusercontent.com/assets/1390124/9894844/883dcba8-5bdd-11e5-989d-de2b2d4c8f6b.png)

**Comment by cklosowski** [comment]
@pippinsplugins and @mindctrl you guys mind messing around with this?

**Comment by cklosowski** [comment]
You'll note in the changesets...we've totally modified the `S3` class further. I think this is just going to have to be a constant. There's too much in there that doesn't play well with the way we use things in WordPress. I've also made our main class a singleton, instead of allowing multiple instances and using relative references (converted `self::` calls to `$this->`, etc)

**Comment by pippinsplugins** [comment]
@cklosowski Could we add error catching / display to the Library tab as well? As a quick test I made my access key invalid and then tried to view the library:
![screen shot 2015-09-16 at 8 17 47 am](https://cloud.githubusercontent.com/assets/1034109/9905603/80ff4bdc-5c4b-11e5-8ae5-b11f425bd4de.png)

That's one of the places we see a lot of people run into issues.

**Comment by cklosowski** [comment]
I think we could do that...i figured that admin notice about it being empty was enough :P

**Comment by mindctrl** [comment]
The admin notice is great, but having the errors show on that screen would be helpful when they enter the wrong keys or there's a permissions problem on the bucket.

**Comment by cklosowski** [comment]
@mindctrl got it, you see the support requests, so i'll add someting in there.

**Comment by cklosowski** [comment]
So if I don't have a key this already shows...so we're wanting invalid keys now?

![screen shot 2015-09-16 at 12 14 34 pm](https://cloud.githubusercontent.com/assets/1390124/9915545/84ebb228-5c6c-11e5-86a9-a10d2b3d2252.png)
![screen shot 2015-09-16 at 12 14 29 pm](https://cloud.githubusercontent.com/assets/1390124/9915544/84e980e8-5c6c-11e5-9645-bf56d02c0060.png)

**Comment by cklosowski** [comment]
And returning an actual error from the S3 api if it fails.
![screen shot 2015-09-16 at 12 21 34 pm](https://cloud.githubusercontent.com/assets/1390124/9915720/7efb3676-5c6d-11e5-8075-48d0eec57521.png)
![screen shot 2015-09-16 at 12 21 25 pm](https://cloud.githubusercontent.com/assets/1390124/9915721/7efea892-5c6d-11e5-8c64-37188aa0b201.png)

**Comment by mindctrl** [comment]
@cklosowski that looks nice. I'll test today.

**Comment by pippinsplugins** [comment]
Perfect. I'm happy with this if @mindctrl is.

**Comment by mindctrl** [comment]
@cklosowski to test this, I deleted the last character off my access key ID.

![image](https://cloud.githubusercontent.com/assets/1254870/9918610/d55ac59a-5c95-11e5-9b0f-9a3b56238c19.png)

Got the nice error. I then added back the proper access key ID and saved. I'm still getting the error about the ID. At one point I got this in the debug.log:
`16-Sep-2015 21:09:29 UTC] PHP Warning:  array_key_exists() expects parameter 2 to be array, boolean given in /wp-content/plugins/edd-amazon-s3/edd_s3.php on line 330`

That message is gone, but for the life of me I can't get my account working again. I even generated new keys and still get that error. Not seeing anything obvious that I'm doing wrong, and I've been using this same account and bucket for months. I don't see how anything you did would cause this, but wanted to log it just in case. Could be temporary. The values in my DB are correct. Thoughts?

**Comment by pippinsplugins** [comment]
@mindctrl do you have a bucket set?

**Comment by cklosowski** [comment]
i've not seen, this, it's exactly how I was testing it, just have to refresh the page that you use the modal on.

if you have a tab for settings, and a tab where the modal is used, you need to udpate the settings, then refresh the modal tab.

**Comment by mindctrl** [comment]
@pippinsplugins yes. It's only happening when trying to browse the existing S3 library. The upload part works.

**Comment by cklosowski** [comment]
@mindctrl ok, I think I see the issue, fixing now

**Comment by cklosowski** [comment]
ok @mindctrl try that out, pull down `issue/15` now

**Comment by mindctrl** [comment]
@cklosowski @pippinsplugins latest commit fixed it.

**Comment by cklosowski** [comment]
Sweet, ready for merge whenever you are @pippinsplugins

**Comment by pippinsplugins** [comment]
Deploy at wiull.

**Comment by cklosowski** [comment]
:+1:
