### ISSUE TITLE
S3 Blocks Regular File Upload to Post Content

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-amazon-s3#2]
When S3 is activated, the regular upload process for normal media files added to the post content no longer work.

**Comment by sunnyratilal** [comment]
@pippinsplugins I can't replicate this. Also, given the date of this issue, I believe the new media uploader should no longer cause this issue.

Good to close?

**Comment by pippinsplugins** [comment]
Close.
