### ISSUE TITLE
Add support for IAM users

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-amazon-s3#20]
Amazon recommends using IAM users now.
![image](https://cloud.githubusercontent.com/assets/1254870/12265794/49b92cb4-b90d-11e5-9143-05b19c95f2df.png)

We've had a number of people that try to use IAM credentials and think the extension is broken. It would be nice to support this.

**Comment by pippinsplugins** [comment]
@cklosowski Let's put this on your radar for soon after Recurring Payments is done.

**Comment by cklosowski** [comment]
:+1:

**Comment by Shelob9** [comment]
For the record I just made it work, as an IAM user. The settings screen, and the documentation say "After logging into your S3 account, click on "Security Credentials" in the sidebar. Scroll down to "Access Credentials" and you will see your Access Key ID. Copy and paste it here." They must have changed their UI, beacuse this isn't a thing anymore.

To make this work, I had to go to IAM section of the AWS console, create a user, and then under that users permissions I attached a policy, "AmazonS3FullAccess". Then I was able to use that users access key id/ secret key and everything connected properly.

**Comment by pippinsplugins** [comment]
@topher1kenobe Could you get the docs updated for this please?

**Comment by pippinsplugins** [comment]
This actually all works perfectly fine. Going off of @Shelob9's comment and my own research, I've worked out how it all works.

New documentation: http://docs.easydigitaldownloads.com/article/1455-amazon-s3-creating-an-iam-user

**Comment by pippinsplugins** [comment]
Updated descriptions in settings too https://github.com/easydigitaldownloads/edd-amazon-s3/commit/2d53d537981e6a28f3f24910edc66736485e497f
