### ISSUE TITLE
Add support for AWS Signature version 4

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-amazon-s3#21]
Newer regions like Frankfurt only support version 4. If you try to use a bucket there, you'll get this error:  `S3::listBuckets(): [InvalidRequest] The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. - /home/xxxxx/www/xxxxxx/wp-content/plugins/edd-amazon-s3/s3.php:389 Code: 0`

Region support:
![image](https://cloud.githubusercontent.com/assets/1254870/12361023/9537bfc4-bb89-11e5-9b09-7519b52684d6.png)

Reference links:
http://docs.aws.amazon.com/general/latest/gr/rande.html

http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

**Comment by pippinsplugins** [comment]
I'd like to hit this up soon after Recurring 2.4 is done.

**Comment by pippinsplugins** [comment]
Just had another ticket on this.

**Comment by pippinsplugins** [comment]
Another customer affected https://secure.helpscout.net/conversation/352422466/57695/?folderId=180499

**Comment by mintplugins** [comment]
Another customer ticket: 
https://secure.helpscout.net/conversation/361938787/58887/

**Comment by brashrebel** [comment]
Another ticket:
https://secure.helpscout.net/conversation/375598482/60493/?folderId=180499

**Comment by sunnyratilal** [comment]
76b94c54ae221d2fcf9561dfd1a368b44abfd237 and 4eac22ccf69bb912f5c81c34c3bc91cc5deb510c have implemented the official AWS SDK which uses Signature v4.

**Comment by sunnyratilal** [comment]
Marked this as `Has PR` because the changes introduced in #53 automatically fix this

**Comment by brashrebel** [comment]
Another ticket:
https://secure.helpscout.net/conversation/403555128/63751/?folderId=448801

**Comment by pippinsplugins** [comment]
This has all been merged into release/2.3 so closing!
