### ISSUE TITLE
S3 should filter the FES File Validation

### ISSUE THREAD

**Issue by chriscct7** [easydigitaldownloads/edd-amazon-s3#22]
The s3 extension should be filtering the FES file validation to tell FES that a file URL is valid. Since FES doesn't maintain any code for s3, it does not know what a valid S3 url looks like, or even if S3 is installed. If s3 needs to use custom urls that do not conform to the RFC's governing PHP's FILTER_URL functionality, s3 should be in charge of telling FES (and other extensions) what is or is not a valid URL. This prevents non-valid URLs from being validated on sites that aren't running s3 and also makes it easier if Amazon ever changes their URL syntax (the one extension every user will expect will need an update, will be the only one needing an update).

There's a filter here:
https://github.com/chriscct7/edd-fes/blob/release/2.4/classes/fields/multiple_pricing.php#L403
it can use, and we can add one here:
https://github.com/chriscct7/edd-fes/blob/release/2.4/classes/fields/multiple_pricing.php#L384
if that'd be easier

**Comment by chriscct7** [comment]
We could add a filter on 384 with something like:
`$valid = apply_filters( 'fes_validate_' . $this->template() . '_field', false, $values[ 'files' ][ $key ] );`

Amazon s3 could then inspect the URL and if its an s3 return true, thus bypassing the error return

**Comment by chriscct7** [comment]
If we move forward like Sean was talking about with greater inter-operability, it'll be much easier to have this in here. Checkout fields manager will probably at some point want to support Amazon s3, and I could see someone wanting to do the same thing in other extensions that deal with file urls like pdf stamper and image watermark and stuff like that.

**Comment by chriscct7** [comment]
It looks like we might need to add the aftormentioned filter.

Here's a problem with the pull request:

Let's say someone uses Amazon s3, and uploads a file using it, but then doesn't fill in (for example) the price field on that row. Without the PR:
FES would validate error with a file error and a empty price field error

After PR
FES would validate error with a file error and a empty price field error. S3 then says "hey that's my file", and returns true, which correctly tells FES the file is valid. However, at the same time because s3 resets all errors (and not just file ones), the user has now submitted a form with an invalid price field because s3 has cleared all field errors.

I think we should add the filter mentioned above to FES, if that looks okay to you, and have s3 use that.

**Comment by chriscct7** [comment]
I think the pr would be something like this:

``` php
$valid = apply_filters( 'fes_validate_' . $this->template() . '_field_files', false, $values[ 'files' ][ $key ] );
if ( ! $valid ) {
    $return_value = __( 'Please enter a valid URL', 'edd_fes' ); 
    break;
}

```

Then s3 could just hook in and return (bool) is_s3_file()

**Comment by chriscct7** [comment]
There's actually 5 distinct issues

First, the filter implemented in the pr doesn't actually use the right value. It seems to take in $values but $values in this case is not the file name, it's the array of all values for that field. The array contains an array for each row. Each row's array contains up to 3 columns ( file/price/option name depending on the settings for multiple price fields. When it's exploding $values, there's no way to tell what exactly that is.

This actually in most cases results in a fatal error:
![image](https://cloud.githubusercontent.com/assets/1324637/12502381/110f47be-c096-11e5-83ce-cf536f8197c4.png)


Second, the filter implemented should probably check to see if the file entered is a valid s3 file. There's no way to tell if someone just simply typed in a file name that might be on amazon or just is doing it for whatever.

Third, as mentioned above, $errors contains only the first error FES has found. In the current scenario if you have a multiple price field with 2 rows, where the first row's price, name and file are filled in, and the second row's price and file (but not name) are filled in, right now what happens is the error FES would normally return to say the name isn't filled in for the second row is missing (this is because FES breaks at the first error, and s3 has overrode that error). This is a result of a poorly implemented, error checking system, but something that s3 will need to take into account. This probably means we need to do this: https://github.com/easydigitaldownloads/edd-amazon-s3/issues/22#issuecomment-173797488
![image](https://cloud.githubusercontent.com/assets/1324637/12502361/d5c94d4e-c095-11e5-8706-45b96f6a7b4f.png)

Fourth, if files are disabled on the pricing field (maybe the store manager turned them off, as its an option on the radio), s3 continues to validate anyways meaning even if a vendor cannot upload files, if they skip entering a price name, Amazon's check actually bypasses that valid error message.

Fifth, if an invalid file extension is not found, the original error message needs to be returned to FES. Right now, if a user enters a filename that is not a valid URL and is not a valid S3 extension, Amazon makes the error bool (false), which doesn't work. FES needs the original string, which is displayed. Also, if it is an S3 file, s3 returns (bool) true, which is actually the opposite of what FES needs. The way validate works as a basic level is as follows:

$has_error = $field->validate();

Where a field that is validated as having no errors returns false. If an error is found, the error message is returned (and subsequently displayed).



Here's what I think needs to happen:
1. In FES we need to do https://github.com/easydigitaldownloads/edd-amazon-s3/issues/22#issuecomment-173797488 (long term we need a better error system, but one thing at a time)
2. In s3, s3 needs to hook into that ^, and return true if its an s3 file, false otherwise. If files are turned off on the multiple pricing field, based on the placement of 1, then the filter won't be called so this solves problems 1, 3, 4 and 5. Ideally 2 needs a better solution (maybe you can call s3 to see if a file of the name entered exists in the bucket?)

**Comment by chriscct7** [comment]
Also the filter should probably not run if s3 isn't setup (credentials not entered) I think

**Comment by pippinsplugins** [comment]
Ok tell me how to fix it and I will. I'm not too concerned with confirming it's a valid s3 URL, just keeping FES from rejecting it.

**Comment by chriscct7** [comment]
If this goes out in FES, s3 should be updated to use this: 
https://github.com/chriscct7/edd-fes/pull/998/files

S3's code would be something like:

```php
add_filter( 'fes_validate_multiple_pricing_field', array( $this, 'bad_url' ), 10, 2 );
function your_function( $is_valid, $file ){
if ( ! $is_valid ){
     $ext   = edd_get_file_extension( $file);
     $is_valid= ! empty( $file); 
  }
return $is_valid;
}
```
