### ISSUE TITLE
Long Filename Issue

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-amazon-s3#3]
https://easydigitaldownloads.com/wp-content/uploads/2013/03/Amazon-S3.png

**Comment by sunnyratilal** [comment]
Will be done in conjunction with #56

**Comment by sunnyratilal** [comment]
This has now been automatically fixed as we're now using WP List Table styling as per #58

**Comment by sunnyratilal** [comment]
![src wordpress-develop dev-wp-admin-post php-post 1296 action edit](https://user-images.githubusercontent.com/1525554/29949167-d245b006-8eaa-11e7-8ea8-37449af23192.png)

**Comment by sunnyratilal** [comment]
![src wordpress-develop dev-wp-admin-post php-post 1296 action edit](https://user-images.githubusercontent.com/1525554/29949183-e2dae5c6-8eaa-11e7-9938-48fe3ab0d005.png)
