### ISSUE TITLE
Links breaking for FES vendors with spaces in usernames

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-amazon-s3#33]
I'm not entirely certain whether this is better resolved in FES or S3 but essentially it appears that URLs to media are not saving properly for vendors with spaces in their usernames.

Here's a ticket: https://secure.helpscout.net/conversation/227047138/38102/?folderId=180499

**Comment by pippinsplugins** [comment]
Just tested and it's working fine for me. I'd guess we fixed it through other changes at some point.
