### ISSUE TITLE
Use user_nicename instead of user_login for S3 folders

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-amazon-s3#36]
When files are sent from FES to Amazon S3, we use the `user_login` for the folder name in the bucket. This works 99.99% of the time but breaks if the `user_login` every contains a space, such as in this ticket https://secure.helpscout.net/conversation/262477496/44487/?folderId=180504

Let's change it to use `user_nicename`, which is specifically meant to be a URL-safe value.

**Comment by pippinsplugins** [comment]
The customer above requested the user ID be used instead.

Perhaps we could make it an option to select which one is used.

**Comment by sunnyratilal** [comment]
PR opened at #63 and ready for testing.
