### ISSUE TITLE
clearstatcache() doesn't expect parameters pre PHP 5.3

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-amazon-s3#41]
Looks like we're not very PHP 5.2 friendly. The [clearstatcache() function here](https://github.com/easydigitaldownloads/edd-amazon-s3/blob/master/s3.php#L580) is given some parameters that were introduced in PHP 5.3 so 5.2 throws errors.

<img width="1310" alt="amazon-s3-problem" src="https://cloud.githubusercontent.com/assets/4993131/20139201/f289528c-a652-11e6-88f0-a0653346d62f.png">

**Comment by pippinsplugins** [comment]
Let's bump Amazon S3 to PHP 5.3 only.

**Comment by pippinsplugins** [comment]
See https://github.com/easydigitaldownloads/edd-amazon-s3/issues/42

**Comment by brashrebel** [comment]
I'll let the reporting customer know that no fix will be coming and they need to upgrade PHP to use S3.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sunnyratilal** [comment]
This issue becomes invalid as we bump the minimum PHP requirement as per #45
