### ISSUE TITLE
Update SDK to Amazon's official PHPSDK

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-amazon-s3#45]
Using AMazon's official SDK should help resolves issues like #21 while also giving us additional features that we can use to improve the plugin.

**Comment by pippinsplugins** [comment]
Hmm, Amazon requires PHP 5.5 or later: http://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/requirements.html

**Comment by pippinsplugins** [comment]
Oh good grief. You can't have _just_ the S3 SDk, you have to have the entire Amazon SDK, which is 8+mbs.

**Comment by sunnyratilal** [comment]
@pippinsplugins This is now ready for testing.

**Comment by sunnyratilal** [comment]
Docs will need to be updated as the AWS SDK has a minimum PHP requirement of 5.5.  This was agreed by @pippinsplugins beforehand.

**Comment by pippinsplugins** [comment]
I'm able to view buckets with the new version but I cannot list files inside of the bucket:

exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "ListObjects" on "https://eddphotos.s3.amazonaws.com/?marker=&max-keys=30&encoding-type=url"; AWS HTTP error: Client error: `GET https://eddphotos.s3.amazonaws.com/?marker=&max-keys=30&encoding-type=url` resulted in a `400 Bad Request` response: AuthorizationHeaderMalformedThe authorization header (truncated...) AuthorizationHeaderMalformed (client): The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2' - AuthorizationHeaderMalformedThe authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'us-west-2B31522F9B421C0D9yxfu5JiseqxaxD/Eu9BPEHRNvMnaSYURFk7Q1uybQa20DOWyVDGVprhR4AvWJ4+FIFzuik5DK74=' GuzzleHttp\Exception\ClientException: Client error: `GET https://eddphotos.s3.amazonaws.com/?marker=&max-keys=30&encoding-type=url` resulted in a `400 Bad Request` response: AuthorizationHeaderMalformedThe authorization header (truncated...) in /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Exception/RequestException.php:113 Stack trace: #0 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run() #5 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick() #6 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true) #7 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #8 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() #9 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #10 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() #11 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #12 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #13 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/Aws/AwsClientTrait.php(59): GuzzleHttp\Promise\Promise->wait() #14 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/Aws/AwsClientTrait.php(78): Aws\AwsClient->execute(Object(Aws\Command)) #15 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/edd_s3.php(559): Aws\AwsClient->__call('listObjects', Array) #16 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/edd_s3.php(392): EDD_Amazon_S3->get_s3_files('', 30) #17 /Users/pippin/Sites/edd/wp-admin/includes/media.php(536): EDD_Amazon_S3->s3_library_tab() #18 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/edd_s3.php(355): wp_iframe(Array) #19 /Users/pippin/Sites/edd/wp-includes/class-wp-hook.php(298): EDD_Amazon_S3->s3_library_iframe('') #20 /Users/pippin/Sites/edd/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #21 /Users/pippin/Sites/edd/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #22 /Users/pippin/Sites/edd/wp-admin/media-upload.php(110): do_action('media_upload_s3...') #23 {main} Next Aws\S3\Exception\S3Exception: Error executing "ListObjects" on "https://eddphotos.s3.amazonaws.com/?marker=&max-keys=30&encoding-type=url"; AWS HTTP error: Client error: `GET https://eddphotos.s3.amazonaws.com/?marker=&max-keys=30&encoding-type=url` resulted in a `400 Bad Request` response: AuthorizationHeaderMalformedThe authorization header (truncated...) AuthorizationHeaderMalformed (client): The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2' - AuthorizationHeaderMalformedThe authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'us-west-2B31522F9B421C0D9yxfu5JiseqxaxD/Eu9BPEHRNvMnaSYURFk7Q1uybQa20DOWyVDGVprhR4AvWJ4+FIFzuik5DK74= in /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/Aws/WrappedHttpHandler.php:192 Stack trace: #0 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/Aws/WrappedHttpHandler.php(97): Aws\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\Psr7\Request), Object(Aws\Command), Array) #1 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(203): Aws\WrappedHttpHandler->Aws\{closure}(Array) #2 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(174): GuzzleHttp\Promise\Promise::callHandler(2, Array, Array) #3 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/RejectedPromise.php(40): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(Array) #4 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/TaskQueue.php(47): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}() #5 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run() #6 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick() #7 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true) #8 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #9 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() #10 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #11 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() #12 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #13 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/GuzzleHttp/Promise/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #14 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/Aws/AwsClientTrait.php(59): GuzzleHttp\Promise\Promise->wait() #15 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/Aws/AwsClientTrait.php(78): Aws\AwsClient->execute(Object(Aws\Command)) #16 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/edd_s3.php(559): Aws\AwsClient->__call('listObjects', Array) #17 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/edd_s3.php(392): EDD_Amazon_S3->get_s3_files('', 30) #18 /Users/pippin/Sites/edd/wp-admin/includes/media.php(536): EDD_Amazon_S3->s3_library_tab() #19 /Users/pippin/Sites/edd/wp-content/plugins/edd-amazon-s3/edd_s3.php(355): wp_iframe(Array) #20 /Users/pippin/Sites/edd/wp-includes/class-wp-hook.php(298): EDD_Amazon_S3->s3_library_iframe('') #21 /Users/pippin/Sites/edd/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #22 /Users/pippin/Sites/edd/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #23 /Users/pippin/Sites/edd/wp-admin/media-upload.php(110): do_action('media_upload_s3...') #24 {main}

**Comment by sunnyratilal** [comment]
@pippinsplugins One thing I forgot to mention is in order to use Signature V4, we have to provide the region of the bucket.  Our EDD bucket is in `us-west-2` so if you go to the S3 settings, you need to select `US West (Oregon)` in order for the signature to use the correct region when it's generated.

**Comment by pippinsplugins** [comment]
@sunnyratilal let's get that set as a default then otherwise we'll be flooded with tickets when this update goes live.

**Comment by pippinsplugins** [comment]
When the API keys are incorrect, we get a fatal error:

 Fatal error: Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "ListBuckets" on "https://s3.amazonaws.com/"; AWS HTTP error: Client error: `GET https://s3.amazonaws.com/` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided (truncated...) InvalidAccessKeyId (client): The AWS Access Key Id you provided does not exist in our records. - <?xml version="1.0" encoding="UTF-8"?> <Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>AKIAIYRNXBU2VDBWEPL</AWSAccessKeyId><RequestId>AD99F7683838F1E4</RequestId><HostId>C6RkpcgID0tv71HUffMUbdDYGUpomh5NX8g7qlExXTvdc+CbXKcTfEv8ohDHH99+6nkPpbhjmDg=</HostId></Error>' exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET https://s3.amazonaws.com/` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>Inval in /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-amazon-s3/aws-sdk/Aws/WrappedHttpHandler.php on line 192. Output triggered in /Users/pippinwilliamson/Sites/edd/wp-content/plugins/query-monitor/collectors/php_errors.php on line 164

Can we catch that error and show a pretty error message please?

**Comment by pippinsplugins** [comment]
I don't think the region setting will work for us. Buckets can each have their own region and if one bucket is in a different region than the one entered in settings, we get a fatal error:

exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "ListObjects" on "https://eddphotos.s3.amazonaws.com/?marker=&max-keys=30&encoding-type=url"; AWS HTTP error: Client error: `GET https://eddphotos.s3.amazonaws.com/?marker=&max-keys=30&encoding-type=url` resulted in a `400 Bad Request` response: AuthorizationHeaderMalformedThe authorization header (truncated...) AuthorizationHeaderMalformed (client): The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'

Since we're able to obtain a list of the buckets, can't we auto detect which region each of them is in?

**Comment by sunnyratilal** [comment]
@pippinsplugins I've removed the region option and updated it to use the `S3MultiRegionClient`

**Comment by sunnyratilal** [comment]
@pippinsplugins Added prettier error messages too

**Comment by pippinsplugins** [comment]
@sunnyratilal looking good.

Browsing and inserting files works well now. Downloading them, however, does not:
<img width="1619" alt="screen shot 2017-07-31 at 2 38 53 pm" src="https://user-images.githubusercontent.com/1034109/28795044-0adf2b10-75fe-11e7-9f7d-c3f46b119728.png">

**Comment by sunnyratilal** [comment]
@pippinsplugins I believe that's an issue with the files in our bucket.  The files that have a preceding slash `/` don't seem to be accessible.

I've tried with other files in the bucket and they seem to work fine.

I'm not sure why some of the files in the `eddtest` bucket have a preceding `/`.

**Comment by pippinsplugins** [comment]
@sunnyratilal We'll need to account for that somehow then. Could we just strip off the first `/`?

**Comment by sunnyratilal** [comment]
@pippinsplugins I just logged in to our bucket and those files with the extra `/` don't show up in the bucket.

Even doing a search using the AWS CLI doesn't seem to pick up those files.

**Comment by pippinsplugins** [comment]
Can you see them when using `master` branch?

**Comment by sunnyratilal** [comment]
Yep but again with a `/` prepended.

**Comment by pippinsplugins** [comment]
That's worrying. Sounds like the previous version somehow made it possible to upload files that end up with a / at the front. That means there is the potential for users to lose access to files they already uploaded . . .

**Comment by sunnyratilal** [comment]
@pippinsplugins it seems that in our S3 bucket, there is a folder called `/` - I'm not sure how that even came to be, seems super odd to allow a folder with those character as its name.

The API concatenates and removes double slashes i.e. `eddtest//` and changes them to `eddtest/` because it assumes that the extra slash has been added mistakenly.

I'm going to go back a few versions of S3 and see if it was our code that allowed this to happen; this directory may have appeared during testing?

**Comment by sunnyratilal** [comment]
Testing with multiple versions of S3, this just doesn't seem possible to have a directory with the name `/`.

The slash is the delimiter used by S3 to separate buckets and folders. I'm still at a loss as to how S3 allowed a directory to be called `/`.

Opening the file from the S3 Web Console works so I'm going to try and see if I can do some encoding work and get it to work.

**Comment by pippinsplugins** [comment]
@sunnyratilal let's ignore it then. If it pops up in support we can deal with it then.

**Comment by sunnyratilal** [comment]
Sounds good - if it does come up in support, all we need to do is to get the customer to move the files out of the directory called `/` and up a level.

**Comment by sunnyratilal** [comment]
@easydigitaldownloads/core-devs Would love some testing on this issue when time allows please

**Comment by SDavisMedia** [comment]
@sunnyratilal are we looking for anything besides making sure basic functionality is still good?

**Comment by sunnyratilal** [comment]
@SDavisMedia Just functionality

**Comment by SDavisMedia** [comment]
This is working really well for me. I tested everything I could think of:

* uploading items to various buckets via edit screen
* selecting items from various buckets via edit screen
* vendor submissions to various buckets (by changing the default bucket between submissions)
* Custom Deliverables integration

Suggest other things if you have them.

**Comment by sunnyratilal** [comment]
I think you've got all of them, thanks!

@pippinsplugins or @cklosowski is there anything either of you feel that's left to be tested? If not, are we good to merge?

**Comment by pippinsplugins** [comment]
@SDavisMedia did you test download files that were uploaded on the previous version of S3?

**Comment by SDavisMedia** [comment]
@pippinsplugins just did. That's working properly as well.

**Comment by pippinsplugins** [comment]
Excellent, let's merge!
