### ISSUE TITLE
Javascript error: cannot read property 'models' of undefined when inserting newly uploaded file

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-amazon-s3#48]
Edit a download - > Insert a File - > Upload to Amazon S3 - > Choose File - > Upload to S3 - > Insert uploaded file into Download

This results in the following in the browser console:
`media-views.js?ver=4.7.5:7732 Uncaught TypeError: Cannot read property 'models' of undefined`

Observed on a customer site and replicated locally.

**Comment by sunnyratilal** [comment]
I can't replicate this - @brashrebel could you try replicating please?
 
Have a feeling it's been fixed in the latest version of WordPress Core.

However, this bug is _usually_ fixed with requiring `media-models` as a dependency of the admin JS.

**Comment by sunnyratilal** [comment]
@brashrebel mind giving this a quick test please on `release/2.3` to see if you still get the error?

**Comment by pippinsplugins** [comment]
@sunnyratilal Kyle is off for a couple of weeks. I've just tested and do not see the error so I'm going to close as fixed.
