### ISSUE TITLE
Unused local variables s3_library_tab method

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-amazon-s3#49]
Few variables which do not appear to be needed:

- [x]  [`$back`](https://github.com/easydigitaldownloads/edd-amazon-s3/blob/master/edd_s3.php#L412)
- [x]  [`$total_items`](https://github.com/easydigitaldownloads/edd-amazon-s3/blob/master/edd_s3.php#L416)
- [x]  [`$first_file`](https://github.com/easydigitaldownloads/edd-amazon-s3/blob/master/edd_s3.php#L430)

**Comment by sunnyratilal** [comment]
PR opened at #54

**Comment by pippinsplugins** [comment]
@sunnyratilal this has broken pagination:
<img width="1454" alt="screen shot 2017-07-26 at 1 24 17 pm" src="https://user-images.githubusercontent.com/1034109/28637054-d2bed13c-7205-11e7-9583-194917b4be73.png">

**Comment by sunnyratilal** [comment]
@pippinsplugins Fixed

**Comment by pippinsplugins** [comment]
I still get a bunch of broken links at the top: https://cloudup.com/cxIs9PQa43C

**Comment by pippinsplugins** [comment]
Nevermind, I just realized this happens on master too and a new issue was opened for it #57

**Comment by pippinsplugins** [comment]
Merged into `release/2.3`.
