### ISSUE TITLE
edd-amazon-s3 not working with edd-fes 2.4

### ISSUE THREAD

**Issue by bindascode** [easydigitaldownloads/edd-amazon-s3#51]
Hi, 
I purchased edd-amazon-s3 2.2.5 & installed and edd-fes 2.4 installed but that is not working. Still uploading files on server through fes "prices & files field " 
In admin that is working fine.
How can i fix this issue. Please help. 

Thanks

**Comment by pippinsplugins** [comment]
@bindascode please open a support ticket: https://easydigitaldownloads.com/support

Github is for development tracking only.
