### ISSUE TITLE
Improve styling

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/edd-amazon-s3#56]
The `View More` button follows the standard styling for chevron icons used across WordPress admin but that button styling doesn't look good when the chevron is replaced with text.

We should either:
1. Replace `View More` with chevrons and static page numbers
2. Change `View More` button to follow a styling of a standard WP Admin button

Thoughts?

**Comment by pippinsplugins** [comment]
We can't do 1 because there is no way to know the total number of pages in the bucket, or at least there wasn't when we first built this. That's why we have pseudo pagination.

**Comment by sunnyratilal** [comment]
I've tried to find a way to find the number of objects in an S3 bucket but it still seems like it's not possible, they have a CLI command that does it but no way to do it from the SDK.

So we'll go with option 2.

**Comment by sunnyratilal** [comment]
Title has been updated to reflect general styling improvements across the plugin - i.e. making sure elements line up, etc.

**Comment by pippinsplugins** [comment]
@sunnyratilal I'm not sure I see any difference. Could you post before and after screenshots?

**Comment by sunnyratilal** [comment]
@pippinsplugins the button changes didn't push

**Comment by sunnyratilal** [comment]
@pippinsplugins the main changes with this PR are to do with the table styles - we weren't using the `thead` and `tbody` elements and apply some inline styling which was removed with #45 

The most noticeable change you'll see is with the button styling, but the table styles have changed subtly to match WordPress Core styles:
![image](https://user-images.githubusercontent.com/1525554/30025286-aecf75ea-916f-11e7-9246-0746254686ef.png)

**Comment by pippinsplugins** [comment]
:+1:
