### ISSUE TITLE
View More button reloads entire iframe

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/edd-amazon-s3#57]
![image](https://user-images.githubusercontent.com/1525554/28645250-be55012c-7254-11e7-8874-64919fdec566.png)

When pressing the `View More` button, the entire frame is reloaded displaying the sidebar buttons twice.

**Comment by pippinsplugins** [comment]
@sunnyratilal I believe this is due to a change in WordPress core.

See https://secure.helpscout.net/conversation/384064397/61397/?folderId=180505 and https://core.trac.wordpress.org/ticket/41388#changelog

**Comment by pippinsplugins** [comment]
Hmmm, I've been trying to make a sample plugin in order to illustrate the problem to the core team but I cannot make the issue happen anywhere except within our Amazon S3 tabs. Example plugin that works fine:

```php
<?php
/*
 * Plugin Name: Media Tab Problem Demo
 */
function my_upload_tab($tabs) {
	$tabs['mytabname'] = "My Tab Name";
	return $tabs;
}
add_filter('media_upload_tabs', 'my_upload_tab');

// call the new tab with wp_iframe
function add_my_new_form() {
	wp_iframe( 'my_new_form' );
}
add_action('media_upload_mytabname', 'add_my_new_form');

// the tab content
function my_new_form() {
	$base = admin_url( 'media-upload.php?post_id=' . absint( $_GET['post_id'] ) . '&tab=mytabname' );
	echo '<p>Example HTML content goes here. <a href="' . esc_url( add_query_arg( 'test', '1', $base ) ) . '">Click here</a></p>';
}
```

**Comment by sunnyratilal** [comment]
@pippinsplugins Found the issue, we make a call to `media_upload_header()` in the `s3_library_tab()` function.  This function outputs the legacy media upload UI.

Initial testing shows removing that function doesn't break any functionality.

**Comment by pippinsplugins** [comment]
Fix confirmed.
