### ISSUE TITLE
Display further file metadata

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/edd-amazon-s3#58]
When #45 is merged, we now have more metadata returned to us from the AWS SDK.

We could better use the space given in the table rather than just display the file name an a button.

I propose the table to look like this:

| File Name                                | Size    | Last Modified    | Owner  | Actions  |
|------------------------------------------|---------|------------------|--------|----------|
| Screen Shot 2014-12-30 at 3.26.15 PM.png | 0.24 mb | 2014-12-30 22:12 | pippin | `Use File` |

Thoughts?

**Comment by sunnyratilal** [comment]
For reference, this is all the data returned to us for a single object.

```php
/Users/sunnyratilal/Sites/edd/wp-content/plugins/edd-amazon-s3/edd_s3.php:562:
array (size=6)
  'Key' => string 'Screen Shot 2014-12-30 at 3.26.15 PM.png' (length=40)
  'LastModified' => 
    object(Aws\Api\DateTimeResult)[2295]
      public 'date' => string '2014-12-30 22:12:55.000000' (length=26)
      public 'timezone_type' => int 2
      public 'timezone' => string 'Z' (length=1)
  'ETag' => string '"2fd167c488df62a5cfaf4b5b01cb8496"' (length=34)
  'Size' => int 242403
  'StorageClass' => string 'STANDARD' (length=8)
  'Owner' => 
    array (size=2)
      'DisplayName' => string 'pippin' (length=6)
      'ID' => string '03998031d2aaf72977597886603f447038afe399007775a53c96bc343c63a9ac' (length=64)

```

**Comment by pippinsplugins** [comment]
Yes yes yes, let's do it.

**Comment by sunnyratilal** [comment]
PR opened at #64 and ready for testing

**Comment by pippinsplugins** [comment]
Looks and works great, merged!

**Comment by misulicus** [comment]
Tested release 2.3 locally and in my "use case" the owner display name is not returned for files only the ID
```
["Owner"]=>
        array(1) {
          ["ID"]=>
          string(64) "cd41096955ca87483e129230de2e7dc5fc37ea5645e155e09f0a62eb9ba7df9a"
        }
```

added an isset cond to display the name on line 625
`'owner'         => isset( $file['Owner']['DisplayName'] ) ? $file['Owner']['DisplayName'] : __( 'N/A', 'edd_s3' )`

**Comment by sunnyratilal** [comment]
Thanks @misulicus!
