### ISSUE TITLE
Uploading mp3/wav files over FES with Amazon s3 plugin

### ISSUE THREAD

**Issue by zeromajstor** [easydigitaldownloads/edd-amazon-s3#61]
Hi,

is there way to make when you upload mp3/wav files over FES using amazon s3 plugin that plugin marks these files in amazon s3 bucket as http headers: **binary/octet-stream** and not **audio/mpeg**, because when customers buys on website that audio product/file,  he gets download link in email or on success page, and when he click on download link it opens in new tab and plays and it should start downloading file.

So what I am trying to say is that you should make that audio files force download and not play in browser when customer clicks on download link.

Is there way to do it manually in plugin file code? Or we need to wait your update?

Thank you,
Regards

**Comment by pippinsplugins** [comment]
@zeromajstor there is not currently a way todo this but it is on our long-term todo list for the Amazon S3 extension.

Since we manage the S3 extension in a different github repository, I'm going to close this one.

**Comment by zeromajstor** [comment]
Cant you/I just edit file of plugin and set that mp3/wav files set automatically to different headers?
