### ISSUE TITLE
Undefined index when no files

### ISSUE THREAD

**Issue by misulicus** [easydigitaldownloads/edd-amazon-s3#69]
When using the release 2.3 branch and no files are in the bucket theres an undefined i error. because of the condition that closes here: https://github.com/easydigitaldownloads/edd-amazon-s3/blob/release/2.3/edd_s3.php#L533
easy fix could be adding an else clause

```
 else {
					echo '<div class="error"><p>'. __( 'No files have been uploaded to Amazon S3 yet. Upload one now!', 'edd_s3' ) . '</p></div>';
					exit;
			}
```

**Comment by sunnyratilal** [comment]
Good catch @misulicus!
