### ISSUE TITLE
Latest update string all occurrences of string, not just first

### ISSUE THREAD

**Issue by thomasgriffin** [easydigitaldownloads/edd-amazon-s3#7]
See my comment on the commit and the code I used to address it: https://github.com/easydigitaldownloads/edd-amazon-s3/commit/49cc50c81c6ff794af87a3f4210da711a3a53782

**Comment by pippinsplugins** [comment]
https://github.com/easydigitaldownloads/edd-amazon-s3/commit/e8c321ad2692bff39f9164c7f7b1cdb21ccf130b
