### ISSUE TITLE
Compatibility with v2 SDK

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/edd-amazon-s3#86]
There are a lot of WordPress plugins that haven't updated to v3 of the AWS SDK.

We need to ensure this plugin is compatible with both versions of the SDK.

We've have numerous instances where our version of the SDK is not loaded first.

**Comment by sunnyratilal** [comment]
@pippinsplugins we have compatibility with the v2 SDK now:

- Viewing buckets
- Listing files
- Uploading files
- Downloading files

**Comment by pippinsplugins** [comment]
PR looks good!

**Comment by sunnyratilal** [comment]
Thanks @pippinsplugins
