### ISSUE TITLE
Pagination breaks when bucket contains just folders

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/edd-amazon-s3#90]
@brashrebel and I have discovered a bug with the pagination.

Originally reported here: https://secure.helpscout.net/conversation/441160799/67635/?folderId=448801

If a bucket contains just folders, pagination breaks and only displays 15 items.

**Comment by pippinsplugins** [comment]
Another customer report https://secure.helpscout.net/conversation/444941581/68102/?folderId=180499

**Comment by pippinsplugins** [comment]
And another report https://secure.helpscout.net/conversation/444514970/68043/?folderId=180499

**Comment by sunnyratilal** [comment]
To test: S3 credentials are located in Trello and use the `eddstructuretest` bucket and the `eddtest` bucket and ensure pagination is working on both.
