### ISSUE TITLE
 Uncaught InvalidArgumentException: Found 1 error while validating the input provided for the GetObject operation: [Key]

### ISSUE THREAD

**Issue by d9media** [easydigitaldownloads/edd-amazon-s3#96]
The following exception was thrown when trying to download a purchase:
```
Notice: Uninitialized string offset: 0 in /var/www/vhosts/xxx.xyz/sub.xxx.xyz/wp-content/plugins/edd-amazon-s3/class-edd-amazon-s3.php on line 900

Notice: Uninitialized string offset: 0 in /var/www/vhosts/xxx.xyz/sub.xxx.xyz/wp-content/plugins/edd-amazon-s3/class-edd-amazon-s3.php on line 811

Fatal error: Uncaught InvalidArgumentException: Found 1 error while validating the input provided for the GetObject operation: [Key] expected string length to be >= 1, but found string length of 0 in /var/www/vhosts/xxx.xyz/sub.xxx.xyz/wp-content/plugins/edd-amazon-s3/vendor/aws/aws-sdk-php/src/Api/Validator.php:65 Stack trace: #0 /var/www/vhosts/xxx.xyz/sub.xxx.xyz/wp-content/plugins/edd-amazon-s3/vendor/aws/aws-sdk-php/src/Middleware.php(79): Aws\Api\Validator->validate('GetObject', Object(Aws\Api\StructureShape), Array) #1 /var/www/vhosts/xxx.xyz/sub.xxx.xyz/wp-content/plugins/edd-amazon-s3/vendor/aws/aws-sdk-php/src/S3/S3Client.php(421): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL) #2 /var/www/vhosts/xxx.xyz/sub.xxx.xyz/wp-content/plugins/edd-amazon-s3/vendor/aws/aws-sdk-php/src/S3/S3Client.php(444): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL) #3 /var/www/vhosts/xxx.xyz/sub.xxx.xyz/wp-content/plugins/edd-amazon-s3/vendor/aws/aws-sdk-php/src/S3/S3Client.php(378): Aws\S3\S3Cli in /var/www/vhosts/xxx.xyz/sub.xxx.xyz/wp-content/plugins/edd-amazon-s3/vendor/aws/aws-sdk-php/src/Api/Validator.php on line 65
```
We are using BasicAuth during development, could that be the cause of the issue?

**Comment by nolannordlund** [comment]
Are there any updates on this bug? I ran into it when trying to update a payment with a custom deliverable. I've been dead in the water since.

**Comment by nolannordlund** [comment]
It looks like it is a conflict with Checkout Fields Manager.  I run into the issue with both plugins enabled but I don't have any issues when CFM is disabled

**Comment by pippinsplugins** [comment]
@nolannordlund does it matter which fields you have registered in CFM or is simply having it active enough to replicate the problem?

**Comment by nolannordlund** [comment]
@pippinsplugins As a matter of fact, yes! It is specifically tied to the File Upload from CFM.  I also found that making the following change to [https://github.com/easydigitaldownloads/edd-amazon-s3/blob/master/class-edd-amazon-s3.php](url) seemed to fix the issue.  I have no idea if there are greater implications from doing so however.

`	public function is_s3_file( $file_name ) {
		if ($file_name == '')
			return false;
		return ( '/' !== $file_name[0] && strpos( $file_name, 'http://' ) === false && strpos( $file_name, 'https://' ) === false && strpos( $file_name, 'ftp://' ) === false ) || false !== ( strpos( $file_name, 'AWSAccessKeyId' ) );
	}`

**Comment by mintplugins** [comment]
Confirmed the bug on `master` and confirmed the fix proposed by @nolannordlund fixes the issue without any apparent side effects when uploading files to amazon or using them.

**Comment by pippinsplugins** [comment]
@mintplugins left a review with requested changes on the PR. Once that is addressed, please push this fix out.
